export const MISSION_CREATING = 'MISSION_CREATING'
export const MISSION_CREATE_SUCCESS = 'MISSION_CREATE_SUCCESS'
export const MISSION_CREATE_ERROR = 'MISSION_CREATE_ERROR'

export const MISSION_REQUESTING = 'MISSION_REQUESTING'
export const MISSION_REQUEST_SUCCESS = 'MISSION_REQUEST_SUCCESS'
export const MISSION_REQUEST_ERROR = 'MISSION_REQUEST_ERROR'
