export const TASK_CREATING = 'TASK_CREATING'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_ERROR = 'TASK_CREATE_ERROR'

export const TASK_REQUESTING = 'TASK_REQUESTING'
export const TASK_REQUEST_SUCCESS = 'TASK_REQUEST_SUCCESS'
export const TASK_REQUEST_ERROR = 'TASK_REQUEST_ERROR'
